kind: ConfigMap
metadata:
  name: grafana-agent-traces
apiVersion: v1
data:
  agent.yaml: |    
    traces:
      configs:
      - name: default
        receivers:
          otlp:
            protocols:
              grpc:
        service_graphs:
          enabled: true
        remote_write:
          - endpoint: https://tempo-prod-08-prod-eu-west-3.grafana.net:443
            basic_auth:
              username: $(Grafana-Traces-User)
              password: $(Grafana-Traces-API-Key)
