apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-agent-traces
  name: grafana-agent-traces
  namespace: telemetry
spec:
  type: ClusterIP
  ports:
  - name: grafana-agent-grpc-traces
    port: 4317
    targetPort: 4317
  - name: http-metrics
    port: 80
    targetPort: 80
  selector:
    name: grafana-agent-traces