apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-agent-metrics
  name: grafana-agent-metrics
  namespace: telemetry
spec:
  clusterIP: None
  ports:
  - name: grafana-agent-http-metrics
    port: 80
    targetPort: 80
  selector:
    name: grafana-agent-metrics