trigger:
  branches:
    include:
    - main
  paths:
    include:
    - grafana-agent-logs

pool:
  vmImage: ubuntu-latest

variables:
- name: Chart.Path
  value: $(Build.Repository.LocalPath)/grafana-agent-logs 

steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: '3.11.0'
      installKubectl: true

  - script: |
      helm lint $(Chart.Path)
    displayName: Lint the Helm Chart

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Chart.Path)'
      artifact: 'helm-chart'
      publishLocation: 'pipeline'
    displayName: Publish Updated Helm Chart to Build Artifacts
    condition: succeeded()